// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Antd_Layout = require("@lab-79/bs-ant-design/src/Antd_Layout.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Antd_Layout.make(undefined, undefined, undefined, /* array */[])), "index");

/*  Not a pure module */
